import { SavedEvent } from "../types/event";
import { CardTemplate, TemplateElement } from "../types/template";
import { FieldDefinition } from "../types/player";
import { PLACEHOLDER_BACKGROUNDS } from "./placeholderBackgrounds";

export function createDefaultEvent(): SavedEvent {
  const defaultFields: FieldDefinition[] = [
    { id: "handle", label: "Handle", type: "text", required: true },
    { id: "pronouns", label: "Pronouns", type: "text" },
    { id: "seed", label: "Seed", type: "text" },
    { id: "location", label: "Location", type: "text" },
    { id: "achievement1", label: "Achievement 1", type: "text" },
    { id: "achievement2", label: "Achievement 2", type: "text" },
    { id: "achievement3", label: "Achievement 3", type: "text" },
    { id: "funFact", label: "Fun Fact", type: "textarea" },
    { id: "playerPhoto", label: "Player Photo", type: "image" },
  ];

  const defaultElements: TemplateElement[] = [
    // Handle - large at top
    {
      id: "handle-element",
      fieldId: "handle",
      type: "text",
      x: 20,
      y: 20,
      width: 300,
      height: 60,
      fontSize: 36,
      fontWeight: "bold",
      color: "#ffffff",
      textAlign: "left",
      visible: true,
    },
    // Pronouns and Seed - top right
    {
      id: "pronouns-element",
      fieldId: "pronouns",
      type: "text",
      x: 350,
      y: 20,
      width: 120,
      height: 30,
      fontSize: 14,
      color: "#e9d5ff",
      backgroundColor: "#ffffff",
      backgroundOpacity: 0.2,
      borderRadius: 9999,
      padding: 8,
      textAlign: "center",
      visible: true,
    },
    {
      id: "seed-element",
      fieldId: "seed",
      type: "text",
      x: 350,
      y: 60,
      width: 120,
      height: 30,
      fontSize: 14,
      color: "#e9d5ff",
      backgroundColor: "#ffffff",
      backgroundOpacity: 0.2,
      borderRadius: 9999,
      padding: 8,
      textAlign: "center",
      visible: true,
    },
    // Location Label
    {
      id: "location-label",
      fieldId: "", // Static label
      type: "text",
      x: 20,
      y: 100,
      width: 460,
      height: 20,
      fontSize: 14,
      fontWeight: "bold",
      color: "#d1d5db",
      textAlign: "left",
      visible: true,
    },
    {
      id: "location-element",
      fieldId: "location",
      type: "text",
      x: 20,
      y: 120,
      width: 460,
      height: 30,
      fontSize: 18,
      color: "#ffffff",
      textAlign: "left",
      visible: true,
    },
    // Achievements Label
    {
      id: "achievements-label",
      fieldId: "",
      type: "text",
      x: 20,
      y: 170,
      width: 460,
      height: 20,
      fontSize: 14,
      fontWeight: "bold",
      color: "#d1d5db",
      textAlign: "left",
      visible: true,
    },
    {
      id: "achievement1-element",
      fieldId: "achievement1",
      type: "text",
      x: 20,
      y: 200,
      width: 460,
      height: 40,
      fontSize: 16,
      color: "#ffffff",
      backgroundColor: "#1f2937",
      backgroundOpacity: 0.5,
      borderWidth: 4,
      borderColor: "#a855f7",
      borderRadius: 8,
      padding: 12,
      visible: true,
    },
    {
      id: "achievement2-element",
      fieldId: "achievement2",
      type: "text",
      x: 20,
      y: 250,
      width: 460,
      height: 40,
      fontSize: 16,
      color: "#ffffff",
      backgroundColor: "#1f2937",
      backgroundOpacity: 0.5,
      borderWidth: 4,
      borderColor: "#a855f7",
      borderRadius: 8,
      padding: 12,
      visible: true,
    },
    {
      id: "achievement3-element",
      fieldId: "achievement3",
      type: "text",
      x: 20,
      y: 300,
      width: 460,
      height: 40,
      fontSize: 16,
      color: "#ffffff",
      backgroundColor: "#1f2937",
      backgroundOpacity: 0.5,
      borderWidth: 4,
      borderColor: "#a855f7",
      borderRadius: 8,
      padding: 12,
      visible: true,
    },
    // Fun Fact Label
    {
      id: "funfact-label",
      fieldId: "",
      type: "text",
      x: 20,
      y: 360,
      width: 460,
      height: 20,
      fontSize: 14,
      fontWeight: "bold",
      color: "#d1d5db",
      textAlign: "left",
      visible: true,
    },
    {
      id: "funfact-element",
      fieldId: "funFact",
      type: "textarea",
      x: 20,
      y: 380,
      width: 460,
      height: 100,
      fontSize: 16,
      color: "#ffffff",
      backgroundColor: "#1f2937",
      backgroundOpacity: 0.3,
      borderColor: "#374151",
      borderWidth: 1,
      borderRadius: 8,
      padding: 16,
      lineHeight: 1.5,
      visible: true,
    },
    // Player Photo
    {
      id: "playerphoto-element",
      fieldId: "playerPhoto",
      type: "image",
      x: 350,
      y: 500,
      width: 120,
      height: 120,
      borderRadius: 8,
      borderColor: "#374151",
      borderWidth: 2,
      visible: true, // Now visible by default
    },
  ];

  const defaultTemplate: CardTemplate = {
    id: "default-vertical-card",
    name: "Default Vertical Player Card",
    width: 500,
    height: 700,
    backgroundImage: undefined,
    backgroundColor: PLACEHOLDER_BACKGROUNDS[0].value,
    elements: defaultElements,
  };

  return {
    version: 3, // Increment version for new structure
    id: crypto.randomUUID(),
    name: "Untitled Event",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    fields: defaultFields,
    template: defaultTemplate,
    players: [],
    fonts: [],
  };
}
